FROM node:slim

RUN apt-get update

RUN apt-get -y install git libgtkextra-dev libgconf2-dev libnss3 libasound2 libxtst-dev libxss1 libatk-bridge2.0-0 libgtk-3-0 cmake clang bison flex xz-utils libfuse-dev libudev-dev pkg-config libc6-dev-i386 libcap2-bin git-lfs libglu1-mesa-dev libcairo2-dev libgl1-mesa-dev libtiff5-dev libfreetype6-dev libxml2-dev libegl1-mesa-dev libfontconfig1-dev libbsd-dev libxrandr-dev libxcursor-dev libgif-dev libpulse-dev libavformat-dev libavcodec-dev libswresample-dev libdbus-1-dev libxkbfile-dev libssl-dev llvm-dev

ENV DISPLAY=:0
ENV XAUTHORITY=/root/.Xauthority

VOLUME /root/.Xauthority:/root/.Xauthority:rw